name: Auto-Update Repository
on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update Metadata
        run: |
          CURRENT_TS=$(date +%s)
          
          # Update timestamps
          jq --arg ts "$CURRENT_TS" '.lastUpdate = ($ts|tonumber)' update.json > tmp.json && mv tmp.json update.json
          jq --arg ts "$CURRENT_TS" '.repositoryInfo.timestamp = ($ts|tonumber)' index.min.json > tmp.json && mv tmp.json index.min.json
          
          # Update version (format: 1.0.YYYYMMDD)
          DATE_VERSION=$(date +'%Y%m%d')
          jq --arg v "1.0.$DATE_VERSION" '.latestVersion = $v' extensions/senkuro.json > tmp.json && mv tmp.json extensions/senkuro.json
      
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update: $(date +'%Y-%m-%d')"
          git push
